### ISSUE TITLE
Not working on IOS

### ISSUE THREAD

**Issue by developer-farhan** [istornz/flutter_gaimon#1]
I copy pasted the example code but for some reason tapping on them does nothing on iPhone 6s+ 15.4.1  I even went into settings and made sure vibration was on

**Comment by istornz** [comment]
Hello, thanks for trying to use Gaimon, however I can't achieve to reproduce the issue.
Can you try to clone the exemple from this repo and run it directly on your device ?
I don't have an iPhone 6S to test :/
Thanks,
Dimitri

**Comment by istornz** [comment]
Closing issue as no response.

Feel free to re-open the issue if the issue persist !
