### ISSUE TITLE
Add .ahab support for Android

### ISSUE THREAD

**Issue by Bassiuz** [istornz/flutter_gaimon#11]
As stated in the readme.md, the support for .ahab files in Android is still missing. To support custom haptic behaviour based on .ahab files on all devices, a Android implementation should be provided as well.

I started on a Pull Request implementing .ahab support on Android. It still has some values that are missing based on the documentation of Apple. Also the only thing that is considered now is the Intensity of an event. The Sharpness is, as far as I know, not something that can be controlled with the vibration api of Android.

https://github.com/istornz/flutter_gaimon/pull/10

@istornz What do you think of the current approach? I intend to add the implementation of missing values as well

**Comment by istornz** [comment]
Hello @Bassiuz 👋 

Thanks a lot for your PR, this is awesome to support both iOS & Android with same .ahap file!
I will check more deeper this week, but it seems very well Implemented 👌

**Comment by Bassiuz** [comment]
@istornz I finished up most of the basic functionality to support a .ahap file in Android. Can you take a look?
