### ISSUE TITLE
Build failed because of a typo in the Android plugin code.

### ISSUE THREAD

**Issue by GwonHyeok** [istornz/flutter_gaimon#3]
Android build fails since version `1.1.0`

The placement of the parameter name and type is incorrect.

https://github.com/istornz/flutter_gaimon/blob/937f0116c66fb2362305c4e62a05305c198eaa5c/android/src/main/kotlin/com/dimitridessus/gaimon/GaimonPlugin.kt#L122

It should be changed to:
```kotlin
fun vibrate(effect: VibrationEffect) { 
```

**Comment by istornz** [comment]
Thanks !
Fixed 👍
