### ISSUE TITLE
Complete the documentation on supported iPhones 

### ISSUE THREAD

**Issue by tvrrp** [istornz/flutter_gaimon#5]
Using custom vibration patterns is only supported on iPhone 8 and newer devices. 
Source – [Introducing Core Haptics - WWDC19 - Videos - Apple Developer](https://developer.apple.com/wwdc19/520). Timecode – 1:50
Using other vibration types like UISelectionFeedbackGenerator, UINotificationFeedbackGenerator, etc. works since iPhone 7.
[Source](https://stackoverflow.com/questions/39564510/check-if-device-supports-uifeedbackgenerator-in-ios-10)
On older iPhones, like 6s, the functionality is not supported at all

**Comment by SethuSenthil** [comment]
iPhone 6S, iPhone SE, and iPhone 7 have all been discontinued already and did not receive iOS 16, and tomorrow in WWDC we will likely get more devices discounted when the iOS 17 beta comes out. Considering the iPhone 6s came out in 2015, nearly 8 and a half years ago, I think oversight is justified.

**Comment by tvrrp** [comment]
Developers come to this repository and wonder why the library doesn't work. Because the documentation omits a list of supported devices.
Also, all popular apps still support iOS 15.

**Comment by istornz** [comment]
Thanks for you issue, I updated the documentation 👍
